from fastapi import APIRouter, Depends, status
from typing import Dict, Any
from app.models.ats import (
    ATSAnalyzeRequest,
    ATSSimulateRequest,
    ATSResultResponse,
    ATSResultListResponse,
)
from app.services.ats_service import ats_service
from app.core.dependencies import get_current_user

router = APIRouter(prefix="/ats", tags=["Explainable ATS & Job Matching"])


@router.get("/test", summary="Test ATS Router")
async def test_ats():
    """
    Verifies ATS compatibility router connectivity.
    """
    return {
        "status": "ok",
        "module": "ats",
        "message": "ATS matching engine router is operational"
    }


@router.post(
    "/analyze",
    response_model=ATSResultResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Analyze Resume vs Job Match"
)
async def analyze_match(
    payload: ATSAnalyzeRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Compares a candidate's uploaded resume with a target job description.
    Computes a 100% deterministic, evidence-backed ATS compatibility score with
    detailed dimensional breakdowns, matched evidence excerpts, and actionable recommendations.
    """
    return ats_service.analyze_match(
        resume_id=payload.resume_id,
        job_id=payload.job_id,
        current_user=current_user
    )


@router.post(
    "/simulate",
    status_code=status.HTTP_200_OK,
    summary="Simulate 'What If?' Score Improvement"
)
async def simulate_score(
    payload: ATSSimulateRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Recalculates ATS score projections when hypothetical verified skills are added.
    """
    return ats_service.simulate_score(
        resume_id=payload.resume_id,
        job_id=payload.job_id,
        added_skills=payload.added_skills,
        current_user=current_user
    )


@router.get(
    "/results",
    response_model=ATSResultListResponse,
    status_code=status.HTTP_200_OK,
    summary="List User's Previous ATS Reports"
)
async def list_ats_results(
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Returns all ATS compatibility match reports generated by the authenticated user.
    """
    return ats_service.get_user_results(current_user)


@router.get(
    "/results/{result_id}",
    response_model=ATSResultResponse,
    status_code=status.HTTP_200_OK,
    summary="Get ATS Report Detail"
)
async def get_ats_result(
    result_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Retrieves the full explainable ATS breakdown and recommendations for a previous match.
    Enforces user ownership.
    """
    return ats_service.get_result(result_id, current_user)


@router.delete(
    "/results/{result_id}",
    status_code=status.HTTP_200_OK,
    summary="Delete ATS Report"
)
async def delete_ats_result(
    result_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Deletes an ATS report record from MongoDB.
    Enforces user ownership.
    """
    return ats_service.delete_result(result_id, current_user)

