import re
import asyncio
from fastapi import APIRouter, Depends, status, Response
from typing import Dict, Any
from app.models.ats import (
    ATSAnalyzeRequest,
    ATSSimulateRequest,
    ATSResultResponse,
    ATSResultListResponse,
    ResumeTailorRequest,
    ResumeTailorResponse,
    SaveTailoredResumeRequest,
    SaveTailoredResumeResponse,
    ResumePDFRequest,
)
from app.services.ats_service import ats_service
from app.core.dependencies import get_current_user

router = APIRouter(prefix="/ats", tags=["Explainable ATS & Job Matching"])


@router.get("/test", summary="Test ATS Router")
async def test_ats():
    """
    Verifies ATS compatibility router connectivity.
    """
    return {
        "status": "ok",
        "module": "ats",
        "message": "ATS matching engine router is operational"
    }


@router.post(
    "/analyze",
    response_model=ATSResultResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Analyze Resume vs Job Match"
)
async def analyze_match(
    payload: ATSAnalyzeRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Compares a candidate's uploaded resume with a target job description.
    Computes a 100% deterministic, evidence-backed ATS compatibility score with
    detailed dimensional breakdowns, matched evidence excerpts, and actionable recommendations.
    """
    return await asyncio.to_thread(
        ats_service.analyze_match,
        resume_id=payload.resume_id,
        job_id=payload.job_id,
        current_user=current_user
    )


@router.post(
    "/simulate",
    status_code=status.HTTP_200_OK,
    summary="Simulate 'What If?' Score Improvement"
)
async def simulate_score(
    payload: ATSSimulateRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Recalculates ATS score projections when hypothetical verified skills are added.
    """
    return await asyncio.to_thread(
        ats_service.simulate_score,
        resume_id=payload.resume_id,
        job_id=payload.job_id,
        added_skills=payload.added_skills,
        current_user=current_user
    )


@router.get(
    "/results",
    response_model=ATSResultListResponse,
    status_code=status.HTTP_200_OK,
    summary="List User's Previous ATS Reports"
)
async def list_ats_results(
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Returns all ATS compatibility match reports generated by the authenticated user.
    """
    return ats_service.get_user_results(current_user)


@router.get(
    "/results/{result_id}",
    response_model=ATSResultResponse,
    status_code=status.HTTP_200_OK,
    summary="Get ATS Report Detail"
)
async def get_ats_result(
    result_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Retrieves the full explainable ATS breakdown and recommendations for a previous match.
    Enforces user ownership.
    """
    return ats_service.get_result(result_id, current_user)


@router.delete(
    "/results/{result_id}",
    status_code=status.HTTP_200_OK,
    summary="Delete ATS Report"
)
async def delete_ats_result(
    result_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Deletes an ATS report record from MongoDB.
    Enforces user ownership.
    """
    return ats_service.delete_result(result_id, current_user)


@router.post(
    "/tailor",
    response_model=ResumeTailorResponse,
    status_code=status.HTTP_200_OK,
    summary="Tailor Resume to Job Description & Boost ATS Score"
)
async def tailor_resume(
    payload: ResumeTailorRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Synthesizes an ATS-tailored resume specifically aligned with a target Job Description.
    Calculates deterministic before/after ATS scores, injected keywords, and rewritten bullet points.
    """
    return await asyncio.to_thread(ats_service.tailor_resume, payload, current_user)


@router.post(
    "/tailor/save",
    response_model=SaveTailoredResumeResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Save & Activate Tailored Resume"
)
async def save_tailored_resume(
    payload: SaveTailoredResumeRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Saves the tailored resume as an official resume in candidate's account,
    optionally activates it as primary resume, and re-evaluates ATS compatibility.
    """
    return await asyncio.to_thread(ats_service.save_tailored_resume, payload, current_user)


@router.post(
    "/tailor/pdf",
    status_code=status.HTTP_200_OK,
    summary="Download Tailored Resume as PDF"
)
async def download_tailored_resume_pdf(
    payload: ResumePDFRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Renders the tailored resume text into an ATS-compliant single-column PDF
    with preserved clickable hyperlinks and returns the binary PDF file.
    """
    pdf_bytes = await asyncio.to_thread(ats_service.generate_tailored_pdf, payload, current_user)
    raw_title = payload.title or "tailored_resume"
    clean_filename = f"{re.sub(r'[^a-zA-Z0-9_]+', '_', raw_title.lower()).strip('_')}.pdf"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="{clean_filename}"'
        }
    )

