from fastapi import APIRouter, Depends, status
from typing import Dict, Any, Optional
from app.models.skill_gap import (
    SkillGapAnalyzeRequest,
    SkillGapSimulateRequest,
    SkillGapAnalysisResponse,
    SkillGapListResponse,
)
from app.services.skill_gap_service import skill_gap_service
from app.core.dependencies import get_current_user

router = APIRouter(prefix="/skill-gaps", tags=["Intelligent Skill Gap Analysis"])


@router.get("/test", summary="Test Skill Gap Router")
async def test_skills():
    """
    Verifies Skill Gap Analysis router connectivity.
    """
    return {
        "status": "ok",
        "module": "skill_gaps",
        "message": "Intelligent Skill Gap Analysis router is operational"
    }


@router.post(
    "/analyze",
    response_model=SkillGapAnalysisResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Analyze Candidate Skill Gaps"
)
async def analyze_skill_gaps(
    payload: SkillGapAnalyzeRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Evaluates candidate preparedness against job requirements, calculating
    current vs required levels, gap size, ATS impact, deterministic priority ranking,
    and a structured learning sequence ("What should I learn first?").
    """
    return skill_gap_service.analyze_gaps(
        resume_id=payload.resume_id,
        job_id=payload.job_id,
        current_user=current_user
    )


@router.post(
    "/simulate",
    status_code=status.HTTP_200_OK,
    summary="Simulate 'What If?' Readiness Improvement"
)
async def simulate_skill_gap_improvement(
    payload: SkillGapSimulateRequest,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Calculates projected ATS readiness score increase when leveling up specific skills.
    """
    return skill_gap_service.simulate_gaps(
        analysis_id=payload.analysis_id,
        resume_id=payload.resume_id,
        job_id=payload.job_id,
        improved_skills=payload.improved_skills,
        current_user=current_user
    )


@router.get(
    "",
    response_model=SkillGapListResponse,
    status_code=status.HTTP_200_OK,
    summary="List User's Skill Gap Reports"
)
async def list_user_skill_gaps(
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Lists all previous Skill Gap analyses generated by the authenticated user.
    """
    return skill_gap_service.get_user_analyses(current_user)


@router.get(
    "/job/{job_id}",
    response_model=SkillGapAnalysisResponse,
    status_code=status.HTTP_200_OK,
    summary="Get Skill Gap Analysis by Job ID"
)
async def get_by_job(
    job_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Retrieves the latest skill gap report for a specific job description.
    """
    return skill_gap_service.get_by_job(job_id, current_user)


@router.get(
    "/resume/{resume_id}",
    response_model=SkillGapAnalysisResponse,
    status_code=status.HTTP_200_OK,
    summary="Get Skill Gap Analysis by Resume ID"
)
async def get_by_resume(
    resume_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Retrieves the latest skill gap report for a specific resume.
    """
    return skill_gap_service.get_by_resume(resume_id, current_user)


@router.get(
    "/{analysis_id}",
    response_model=SkillGapAnalysisResponse,
    status_code=status.HTTP_200_OK,
    summary="Get Skill Gap Analysis Detail"
)
async def get_skill_gap_detail(
    analysis_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Retrieves complete skill gap analysis details, including priority ranking,
    evidence, and recommended learning sequence. Enforces user ownership.
    """
    return skill_gap_service.get_analysis(analysis_id, current_user)


@router.delete(
    "/{analysis_id}",
    status_code=status.HTTP_200_OK,
    summary="Delete Skill Gap Report"
)
async def delete_skill_gap(
    analysis_id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Deletes a skill gap report from MongoDB. Enforces user ownership.
    """
    return skill_gap_service.delete_analysis(analysis_id, current_user)
